# Generated by Django 5.1.1 on 2024-10-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_tigersapp', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mi',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
