# Generated by Django 5.1.1 on 2024-10-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_tigersapp', '0003_alter_customer_mi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mi',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
