# Generated by Django 5.1.2 on 2024-10-12 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('OrderNumber', models.AutoField(primary_key=True, serialize=False, verbose_name='Order Number')),
                ('ItemName', models.TextField(verbose_name='Item Name')),
                ('Price', models.FloatField(verbose_name='Price')),
                ('Qty', models.IntegerField(verbose_name='Stock Qty')),
                ('image_url', models.CharField(max_length=2083, verbose_name='Image URL')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
