# Generated by Django 5.1.2 on 2024-10-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('OrderNumber', models.AutoField(primary_key=True, serialize=False, verbose_name='Order Number')),
                ('ItemName', models.TextField(null=True, verbose_name='Item Name')),
                ('Price', models.FloatField(null=True, verbose_name='Price')),
                ('Qty', models.IntegerField(null=True, verbose_name='Stock Qty')),
                ('image_url', models.CharField(max_length=2083, null=True, verbose_name='Image URL')),
            ],
        ),
    ]
