# Generated by Django 5.1.2 on 2024-10-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customerorders_orderdetail_delete_orderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='ShippingAddress',
        ),
        migrations.AddField(
            model_name='customerorders',
            name='ShippingAddress',
            field=models.TextField(null=True, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='OrderDate',
            field=models.TimeField(default='2024-10-16 14:48:34', verbose_name='Date Ordered'),
        ),
    ]
