# Generated by Django 5.1.2 on 2024-10-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderdetail_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='OrderDate',
            field=models.TimeField(default='2024-10-16 14:50:13', verbose_name='Date Ordered'),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='ShippingAddress',
            field=models.CharField(max_length=255, null=True, verbose_name='Shipping Address'),
        ),
    ]
