# Generated by Django 5.1.2 on 2024-10-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_customerorders_orderdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='OrderDate',
            field=models.DateTimeField(default='2024-10-16 15:14:24', verbose_name='Date Ordered'),
        ),
    ]
