# Generated by Django 5.1.2 on 2024-10-16 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_customerorders_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='OrderDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Ordered'),
        ),
    ]
