# Generated by Django 5.1.2 on 2024-10-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_customerorders_itemsordered_delete_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='ItemsOrdered',
            field=models.JSONField(default=list, verbose_name='ItemsOrdered'),
        ),
    ]
