# Generated by Django 5.1.2 on 2024-10-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_customerorders_itemsordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='ItemsOrdered',
            field=models.JSONField(default=dict, verbose_name='ItemsOrdered'),
        ),
    ]
